baseURL = "/"
languageCode = "en-us"
title = "r/stlouisblues Discord"
themesDir = "themes"
theme = "hugo-whisper-theme"
disableKinds = ["taxonomy", "taxonomyTerm"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Info"
    url = "/info/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/info'
  homepage_button_text = 'Read More'
  homepage_intro = 'This is the home of the r/stlouisblues Discord. Here you can find rules and additional info.'
  homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "This is the home of the r/stlouisblues Discord."
    meta_og_title = "r/stlouisblues Discord"
    meta_og_type = "website"
    meta_og_url = "https://rstlouisblues.netlify.com/"
    meta_og_description = "This is the home of the r/stlouisblues Discord."
    meta_twitter_card = "summary"

  [params.logo]
      mobile = "/images/trumpet.png"
      standard  = "/images/4324_st_louis_blues-wordmark-1996.png"
